language: objective-c
osx_image: xcode9
before_install:
- sudo systemsetup -settimezone Asia/Tokyo
install:
- bundle install --path=vendor/bundle --binstubs=vendor/bin
script:
- xcodebuild -project PlayNow.xcodeproj -scheme PlayNow archive -archivePath PlayNow.xcarchive|bundle exec xcpretty
branches:
  only:
  - master
  - "/^\\d+\\.\\d+(\\.\\d+)?$/"
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
  - secure: l5y5s9q1luCvCAgpo32LFzf7IeBmUloI3JQJO4cONzwq+L0Yms9mf3F3x5REuIYOW/Q5E049JIHD3ZzsSsA0md/h+LokSCofmUYR4sZQHLiJaVzYh/vz5232RzrcuZUVMR32xcMU9hzZcgrqwgzN8w8YNA/CS5JXYTFko37F8Tf8CvVBcp1JKLlZB8dpvyBodrY9Xwr7I4Li/EDhqYkdbjOP8LSeo16o1ad88bkCxZNbNefmc2WpuXE0bw+yRL+OBjWz2o0BB53Lbpcv4dgLuJcaCI0rD/TT+G1moKAgpkSxyFuAast7pfngMvy+2FzxX5Nofk9NCQWaAaUb+sfYP/d7T1XJ1vppORqK93RTz3VsptuPvptQgWHgJKqy7HpBNNK5Rn9Nt2VQZ7EDWmF/gMIv6VoMI5HWcKoXpM7H/lmmIpflrNH7tsijSs9wW80kjSS/PSHF9rWUACsj7U6mtdbskwEvmIklCV7zXoVEO5DjYzpxn2WQWCVP4RHezl+rWiciCWgttkkEY+MnWFdRoTj8ea+umKSHwT/pcoqBLgpxWJqIn2wLKWBXp/ToUntBj3+Lq9lpHMm8HOQ39MBuGMvevBbI5R2lwX2eNWlLR8aJQSvTu77gWGje8CCNBAv8O0YrxlqeTXaAQKuR72VKLCemrOMSpKyYFHw1800V+JQ=
before_deploy:
- export/add-keychain.sh
- xcodebuild -exportArchive -archivePath PlayNow.xcarchive -exportPath . -exportOptionsPlist export/options.plist|bundle exec xcpretty
- zip -r --symlinks PlayNow-$TRAVIS_TAG.zip PlayNow.app
deploy:
  provider: releases
  api_key:
    secure: SDMF4wiUTz2Ls+WsM7wzENrLNdWauvCuqTRICdUL8K+nj5uuuMUP09QUVi0zUSJV/9yxAac5ke6nzl5id5R2PxDplLp2CVrwYYjaAVuDi352mdCuDgqAgZqSGm9oqewbD3EVYr3kZ0aJ29bP7oI9NAafc7khKAZBlhjAnXU7Rkbie/Mkw5tKyK55z5QPRqtBGAosodE7kobgidw0HtCQ3oDZMxIksPrWI4j7iXeBBV0Nycinzox0jnxTYhNqovYBLJaiCaW1HE0blUuLfvEdvN20NDgITOvBC2vkfr/mO7BN5XHjFBlRl72LlC6WM+aBfYWS7lb9lNuxFj3HjcZlGSz70tb1RrRbCBsuekSpfLpjChlnWkyaeMkIEx4C0iYxRTVJvxoeicxxEYSN/Ep5nJuUbp8Nkum7Ej15qVyrGo/A0Y3/UvZdvjuOuD7r2nh0ie7ia4dEq3lZ+WMd3y31kZgRm2GfMzLi/H9FmVuD9stbya1SIKG/84FllV35rmD2kTd8l1cvxgkacAbHgR+DxcSzA0R6eHQ6U09Us3EAXQpVBmdEATn/D6HgipBwdkI4WwYV6seOMLSr8lu1Av8eJNO8P3AOh2yX71CMIgy2TlRBzJ+HBjd7VzGZ19yO+QLrw7s6nD9wJH6OQdGXWl7EBxuwezgMaflLLwPlHnPEoSg=
  file: PlayNow-$TRAVIS_TAG.zip
  on:
    tags: true
  skip_cleanup: true
after_deploy:
- export/remove-keychain.sh
notifications:
  webhooks:
    secure: RruAoNWvJR2K+4YhB6SCr7n52KjwxksJ2tW9DO/NgJ8KiunnBwWKmxocNHu7OiqHW8bRnGUmNfQYgBhA0jy5YzDWJCiklZLxXr/WIOvFBD5P5SIBuKdQYU1jnnFw+U1QPETLuQAqzLsCK+5Gw3QmZnF2NPvkMYpRmdwuIV2XSctSqi1Ulp6VZO0qxCbcTFHiXN2s3+pvlLQHuQitncEPbOp3UfUOEdSeroUcKk5B0J+OHYJjZqFjENlWV+CgK6kfRRvQpV0yS8RfQL9xCxOa7bJN4eu3s04dkjzrlYdyKNijWyyX/HE6VndSaLxiBH6nje1eCibO0yIiovP3UVRb2HXUFM8cJy/1MqtPNeeuz2xLXqHZOWAmtRBXHsBsISFRsB6LBoywtbbbsD0aavBRwUgX53ouDxt+E1WwpBJSKbkWjxewDK4EEdfMNPhOJY74N9elkpI2P5i3xr2cwq55T3h/D8wH8E5zYddbowPEXp0A+QiBRJVfIUp6axQHDV9zKJRT3odzUIwWVuEo7oivX8Ql2OX4y07EpGTErD07Pev58kC2OR+7dLrgMyQXHy9YZvPqgC175c1R85F2D79th1XorCvKMcgpp4g2gqSpzhb09pUwEhnnr0XPJHxFKWw1uqR84K3DbWR/TRCeW130ZQYw7haof4uGR1K6JSiHvdg=
